### ISSUE TITLE
zh-cn.json

### ISSUE THREAD

**Issue by yoaan** [xpoi5010/Kartrider-File-Reader#6]
{
    "LanguageName": "zh-tw",
    "DisplayName": "简体中文",
    "StringBags": [
        {
            "Name": "menu_file",
            "Value": "菜单"
        },
        {
            "Name": "menu_export",
            "Value": "导出"
        },
        {
            "Name": "menu_about",
            "Value": "关于"
        },
        {
            "Name": "menu_open",
            "Value": "开启"
        },
        {
            "Name": "menu_save",
            "Value": "保存数据(暂不支持)"
        },
        {
            "Name": "menu_saveas",
            "Value": "另存数据(暂不支持)"
        },
        {
            "Name": "menu_exit",
            "Value": "退出"
        },
        {
            "Name": "menu_exportall",
            "Value": "全部导出"
        },
        {
            "Name": "col_name",
            "Value": "名称"
        },
        {
            "Name": "col_index",
            "Value": "索引"
        },
        {
            "Name": "col_type",
            "Value": "类型"
        },
        {
            "Name": "msg_PlzOpenJMDFileFirst",
            "Value": "请先开启JMD档案，方可进行本操作。"
        },
        {
            "Name": "listview_item2_file",
            "Value": "档案"
        },
        {
            "Name": "listview_item2_folder",
            "Value": "资料夹"
        },
        {
            "Name": "title",
            "Value": "Rho载入器"
        },
        {
            "Name": "menu_Languages",
            "Value": "语言"
        },
        {
            "Name":"filemenu_exportfile",
            "Value":"导出这个文件"
        },
        {
            "Name":"filemenu_convertPng",
            "Value":"转换此文件至PNG"
        },
        {
            "Name":"menu_exportnow",
            "Value":"输出这个资料夹"
        },
        {
            "Name":"msg_cancelExport",
            "Value":"您確定要取消导出吗?\r\n按[是] 以取消。\r\n按[否]以继续。"
        }
        

    ]
}

**Comment by yoaan** [comment]
{
"LanguageName": "zh-cn",
"DisplayName": "简体中文",
"StringBags": [
{
"Name": "menu_file",
"Value": "菜单"
},
{
"Name": "menu_export",
"Value": "导出"
},
{
"Name": "menu_about",
"Value": "关于"
},
{
"Name": "menu_open",
"Value": "开启"
},
{
"Name": "menu_save",
"Value": "保存文件(暂不支持)"
},
{
"Name": "menu_saveas",
"Value": "另存为(暂不支持)"
},
{
"Name": "menu_exit",
"Value": "退出"
},
{
"Name": "menu_exportall",
"Value": "全部导出"
},
{
"Name": "col_name",
"Value": "名称"
},
{
"Name": "col_index",
"Value": "文件大小"
},
{
"Name": "col_type",
"Value": "类型"
},
{
"Name": "msg_PlzOpenJMDFileFirst",
"Value": "请先开启Rho档案，方可进行本操作。"
},
{
"Name": "listview_item2_file",
"Value": "文件"
},
{
"Name": "listview_item2_folder",
"Value": "文件夹"
},
{
"Name": "title",
"Value": "Rho载入器"
},
{
"Name": "menu_Languages",
"Value": "语言"
},
{
"Name":"filemenu_exportfile",
"Value":"导出这个文件"
},
{
"Name":"filemenu_convertPng",
"Value":"转换此文件至PNG"
},
{
"Name":"menu_exportnow",
"Value":"导出这个文件夹"
},
{
"Name":"msg_cancelExport",
"Value":"您確定要取消导出吗?\r\n按[是] 以取消。\r\n按[否]以继续。"
}

]
}

**Comment by xpoi5010** [comment]
已將部分翻譯整合至最新版本23.1.31了。
感謝您的翻譯
