### ISSUE TITLE
可不可以批量解包

### ISSUE THREAD

**Issue by yoaan** [xpoi5010/Kartrider-File-Reader#9]
可不可以批量解包
另外再做个记忆语言功能

**Comment by xpoi5010** [comment]
關於批量解包的部分，在版本23.1.31中，由於「开启Data文件夾」會將所有跑跑卡丁車的檔案開啟，所以可藉由選取多個資料夾實現批量解包Rho、Rho5的功能，甚至將所有檔案一次導出。
而記憶語言的功能也在版本23.1.31加進去了。
感謝您的建議!
